/**
 * Utilities for working with unified diff previews generated by buildDiffPreview.
 *
 * The diff format is a simplified single-hunk unified diff:
 * ```
 * --- a/filePath  (or /dev/null for new files)
 * +++ b/filePath
 * @@ -oldStart,oldLen +newStart,newLen @@
 *  context_before      (optional, one line with " " prefix)
 * -removed_line_1
 * -removed_line_2
 * +added_line_1
 * +added_line_2
 *  context_after       (optional, one line with " " prefix)
 * ```
 */

interface ParsedDiff {
  isNewFile: boolean;
  removedLines: string[];
  addedLines: string[];
  contextBefore: string[];
  contextAfter: string[];
}

/**
 * Parse the simplified unified diff from buildDiffPreview into structured data.
 */
export function parseDiff(diffText: string): ParsedDiff {
  const diffLines = diffText.split("\n");

  const isNewFile = diffLines[0]?.includes("/dev/null") ?? false;

  // Find hunk header index
  let i = 0;
  while (i < diffLines.length && !diffLines[i].startsWith("@@")) {
    i++;
  }

  const contextBefore: string[] = [];
  const removedLines: string[] = [];
  const addedLines: string[] = [];
  const contextAfter: string[] = [];

  // State machine: before → removed → added → after
  enum State {
    ContextBefore,
    Removed,
    Added,
    ContextAfter,
    Done,
  }

  let state: State = State.ContextBefore;

  for (i = i + 1; i < diffLines.length; i++) {
    const line = diffLines[i];

    // Handle truncation marker
    if (line === "...") break;

    if (line.length === 0) continue;

    const prefix = line[0];
    const content = line.slice(1);

    switch (state) {
      case State.ContextBefore:
        if (prefix === " ") {
          contextBefore.push(content);
          state = State.Removed;
        } else if (prefix === "-") {
          removedLines.push(content);
          state = State.Removed;
        }
        break;
      case State.Removed:
        if (prefix === "-") {
          removedLines.push(content);
        } else if (prefix === "+") {
          addedLines.push(content);
          state = State.Added;
        } else if (prefix === " ") {
          contextAfter.push(content);
          state = State.ContextAfter;
        }
        break;
      case State.Added:
        if (prefix === "+") {
          addedLines.push(content);
        } else if (prefix === " ") {
          contextAfter.push(content);
          state = State.ContextAfter;
        }
        break;
      case State.ContextAfter:
        if (prefix === " ") {
          contextAfter.push(content);
        }
        break;
    }
  }

  return { isNewFile, removedLines, addedLines, contextBefore, contextAfter };
}

/**
 * Given the current file content (after the edit was applied) and the diff
 * preview, compute the original content (before the edit).
 *
 * Returns null if the reconstruction fails (e.g., content no longer matches).
 */
export function reverseApplyDiff(modifiedContent: string, diffText: string): string | null {
  const diff = parseDiff(diffText);

  // New file: original is empty
  if (diff.isNewFile) {
    return "";
  }

  const modifiedLines = modifiedContent.split("\n");

  // Build the anchor pattern: contextBefore + addedLines
  const anchor = [...diff.contextBefore, ...diff.addedLines];

  if (anchor.length === 0 && diff.contextAfter.length === 0) {
    // No identifiable anchor, probably an empty diff
    return modifiedContent;
  }

  // Find the anchor in modified content
  let anchorStart = -1;
  for (let j = 0; j <= modifiedLines.length - anchor.length; j++) {
    let match = true;
    for (let k = 0; k < anchor.length; k++) {
      if (modifiedLines[j + k] !== anchor[k]) {
        match = false;
        break;
      }
    }
    if (match) {
      // Verify contextAfter follows after the anchor
      const afterStart = j + anchor.length;
      if (diff.contextAfter.length === 0) {
        anchorStart = j;
        break;
      }
      if (afterStart + diff.contextAfter.length <= modifiedLines.length) {
        let afterMatch = true;
        for (let k = 0; k < diff.contextAfter.length; k++) {
          if (modifiedLines[afterStart + k] !== diff.contextAfter[k]) {
            afterMatch = false;
            break;
          }
        }
        if (afterMatch) {
          anchorStart = j;
          break;
        }
      }
    }
  }

  if (anchorStart === -1) {
    // Try a looser match: find just the contextBefore
    if (diff.contextBefore.length > 0) {
      for (let j = 0; j <= modifiedLines.length - 1; j++) {
        if (modifiedLines[j] === diff.contextBefore[0]) {
          anchorStart = j;
          break;
        }
      }
    }

    if (anchorStart === -1) {
      return null; // Could not reconstruct
    }
  }

  // Reconstruct original:
  // Lines before anchor + contextBefore + removedLines + contextAfter + lines after changed region
  const beforeAnchor = modifiedLines.slice(0, anchorStart);
  const changedEnd = anchorStart + diff.contextBefore.length + diff.addedLines.length + diff.contextAfter.length;
  const afterChanged = modifiedLines.slice(changedEnd);

  const original: string[] = [...beforeAnchor, ...diff.contextBefore, ...diff.removedLines, ...diff.contextAfter];

  // Remove trailing empty line that may have been added by split()
  if (afterChanged.length === 1 && afterChanged[0] === "") {
    // Modified has trailing newline, will be rejoined naturally
  } else if (afterChanged.length > 0) {
    original.push(...afterChanged);
  }

  // Handle trailing newline: if modified content ends with \n, ensure original does too
  const result = original.join("\n");
  if (modifiedContent.endsWith("\n") && !result.endsWith("\n")) {
    return result + "\n";
  }
  if (!modifiedContent.endsWith("\n") && result.endsWith("\n")) {
    return result.slice(0, -1);
  }

  return result;
}
